name: Ping Render Server

on:
  schedule:
    - cron: '*/10 * * * *' # Каждые 10 минут

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send Ping Request
        run: |
          curl -X GET https://your-render-app.onrender.com/ping
